// BullrunIQ — one-click unsubscribe.
// Accepts an optional signed token (?t=...) generated by _shared.signUnsub.
// Tokens make it harder to enumerate or forge unsubscribe links; old links
// without a token are still honoured for backward compatibility.

const { esc, verifyUnsub } = require("./_shared");

function page(msg) {
  return "<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>Unsubscribed — BullrunIQ</title></head>"
    + "<body style='background:#050505;color:#f0ece4;font-family:-apple-system,Segoe UI,sans-serif;text-align:center;padding:90px 24px'>"
    + "<div style='font-family:Georgia,serif;font-size:22px;letter-spacing:2px;margin-bottom:32px'>Bullrun<span style='color:#c9a84c'>IQ</span></div>"
    + "<h1 style='font-family:Georgia,serif;font-weight:400;font-size:30px;color:#c9a84c;margin-bottom:12px'>You're unsubscribed</h1>"
    + "<p style='color:#8a8278;font-size:15px;max-width:420px;margin:0 auto 28px;line-height:1.7'>" + esc(msg) + "</p>"
    + "<a href='https://bullruniq.com' style='display:inline-block;border:1px solid #2a2a2a;border-radius:4px;color:#8a8278;text-decoration:none;padding:12px 28px;font-size:12px;letter-spacing:1.5px;text-transform:uppercase'>← bullruniq.com</a>"
    + "</body></html>";
}

function errorPage(msg) {
  return "<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>Error — BullrunIQ</title></head>"
    + "<body style='background:#050505;color:#f0ece4;font-family:-apple-system,Segoe UI,sans-serif;text-align:center;padding:90px 24px'>"
    + "<div style='font-family:Georgia,serif;font-size:22px;letter-spacing:2px;margin-bottom:32px'>Bullrun<span style='color:#c9a84c'>IQ</span></div>"
    + "<h1 style='font-family:Georgia,serif;font-weight:400;font-size:30px;color:#e05555;margin-bottom:12px'>Invalid link</h1>"
    + "<p style='color:#8a8278;font-size:15px;max-width:420px;margin:0 auto 28px;line-height:1.7'>" + esc(msg) + "</p>"
    + "<a href='https://bullruniq.com' style='display:inline-block;border:1px solid #2a2a2a;border-radius:4px;color:#8a8278;text-decoration:none;padding:12px 28px;font-size:12px;letter-spacing:1.5px;text-transform:uppercase'>← bullruniq.com</a>"
    + "</body></html>";
}

function isValidEmail(s) {
  return typeof s === "string" && s.length > 0 && s.length <= 200 && s.indexOf("@") > 0;
}

exports.handler = async function (event) {
  const params = event.queryStringParameters || {};
  const raw = String(params.email || "").trim().toLowerCase();
  const email = isValidEmail(raw) ? raw : "";
  const tok = String(params.t || "").trim();

  // If a token is present, verify it before proceeding (prevents link forgery).
  // No token → allow (backward-compat with older email links that pre-date signed URLs).
  if (tok && email && !verifyUnsub(email, tok)) {
    return {
      statusCode: 400,
      headers: { "Content-Type": "text/html; charset=utf-8" },
      body: errorPage("This unsubscribe link is invalid or has expired. If you want to unsubscribe, use the link in a recent BullrunIQ email."),
    };
  }

  let storageOk = true;
  try {
    if (email) {
      const blobs = require("@netlify/blobs");
      try { blobs.connectLambda(event); } catch (e) {}
      await blobs.getStore("subscribers").delete(email);
      console.log("[subscribers] removed", email);
    }
  } catch (e) {
    storageOk = false;
    console.log("[unsubscribe] error", e.message);
  }
  return {
    statusCode: 200,
    headers: { "Content-Type": "text/html; charset=utf-8" },
    body: page(email ? (email + " won't receive any more BullrunIQ emails.") : "You won't receive any more BullrunIQ emails.")
      + "<!-- blobs:" + (storageOk ? "ok" : "err") + " -->",
  };
};
