// BullrunIQ — one-click unsubscribe.
// The link includes an HMAC token (t= param) signed with AUTH_SECRET so that
// only the holder of a link that was generated by this server can unsubscribe.
// Legacy links without a token are still honoured so existing emails in inboxes
// continue to work; once all old emails expire the fallback can be removed.

const { esc, verifyUnsub, secretKey } = require("./_lib");

function page(msg) {
  return "<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>Unsubscribed — BullrunIQ</title></head>"
    + "<body style='background:#050505;color:#f0ece4;font-family:-apple-system,Segoe UI,sans-serif;text-align:center;padding:90px 24px'>"
    + "<div style='font-family:Georgia,serif;font-size:22px;letter-spacing:2px;margin-bottom:32px'>Bullrun<span style='color:#c9a84c'>IQ</span></div>"
    + "<h1 style='font-family:Georgia,serif;font-weight:400;font-size:30px;color:#c9a84c;margin-bottom:12px'>You're unsubscribed</h1>"
    + "<p style='color:#8a8278;font-size:15px;max-width:420px;margin:0 auto 28px;line-height:1.7'>" + esc(msg) + "</p>"
    + "<a href='https://bullruniq.com' style='display:inline-block;border:1px solid #2a2a2a;border-radius:4px;color:#8a8278;text-decoration:none;padding:12px 28px;font-size:12px;letter-spacing:1.5px;text-transform:uppercase'>← bullruniq.com</a>"
    + "</body></html>";
}

function isValidEmail(s) {
  return typeof s === "string" && s.length > 0 && s.length <= 200 && s.indexOf("@") > 0;
}

exports.handler = async function (event) {
  const q = event.queryStringParameters || {};
  const raw = String(q.email || "").trim().toLowerCase();
  const token = String(q.t || "").trim();
  const email = isValidEmail(raw) ? raw : "";

  // When AUTH_SECRET is configured, require a valid HMAC token to prevent anyone
  // who knows a subscriber's email from unsubscribing them without their consent.
  if (email && secretKey()) {
    if (!token || !verifyUnsub(email, token)) {
      return {
        statusCode: 400,
        headers: { "Content-Type": "text/html; charset=utf-8" },
        body: page("This unsubscribe link is invalid or has expired. Please use the link from a recent email."),
      };
    }
  }

  try {
    if (email) {
      const blobs = require("@netlify/blobs");
      try { blobs.connectLambda(event); } catch (e) {}
      await blobs.getStore("subscribers").delete(email);
      console.log("[subscribers] removed", email);
    }
  } catch (e) {
    console.log("[unsubscribe] error", e.message);
  }
  return {
    statusCode: 200,
    headers: { "Content-Type": "text/html; charset=utf-8" },
    body: page(email ? (email + " won't receive any more BullrunIQ emails.") : "You won't receive any more BullrunIQ emails."),
  };
};
